User Profile with Animation
2110336-2565-2/sec2-group11-trainder-frontend pull request #10
Opened 2023-02-08 14:05 UTC by tnptw

2023-02-08 15:23 UTC, nnanthicha requested changes

2023-02-08 15:23 UTC, nnanthicha commented on src/pages/account/profile.tsx
> +      <div className="flex bg-blue h-screen justify-center">
put "bg-blue h-screen" before navbar ?

2023-02-08 15:56 UTC, noppakorn requested changes

2023-02-08 15:56 UTC, noppakorn commented on src/pages/account/profile.tsx
> +                <strong>{profile?.birthdate.toString().split("T")[0]}</strong>
can you also show date in a more beautiful manner?

2023-02-09 04:51 UTC, nnanthicha approved these changes

2023-02-09 05:08 UTC, noppakorn requested changes

2023-02-09 05:08 UTC, noppakorn commented on src/pages/account/profile.tsx
> +  };
Why are you doing this? In `UserProfile` the birthdate is a `Date` object right? Couldn't you just use the built-in method? [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)

2023-02-09 05:08 UTC, noppakorn commented on src/pages/account/profile.tsx
> +    const gender_first = profile?.gender[0].toUpperCase();
prefer camelCase

2023-02-09 05:57 UTC, noppakorn approved these changes

2023-02-09 05:57 UTC, merged