Update first version
2110336-2565-2/sec2-group11-trainder-frontend pull request #12
Opened 2023-02-08 17:03 UTC by naphatbass

- added map just for measure map size
- changed function to arrow
- chat and calendar button is not added yet

2023-02-08 17:14 UTC, noppakorn requested changes
Also, merge the main branch into your branch and request review again.

2023-02-08 17:14 UTC, noppakorn commented on src/pages/_app.tsx
> +    const publicPaths = ["/", "/account/signup","/user/booking/profile"];
This is for debug right? Remove it from the public path.

2023-02-09 01:10 UTC, nnanthicha commented on src/pages/user/booking/profile.tsx
> +              <img src="/back_icon.png" className=" object-contain w-10 "  />
you can use icon from @heroicons/react/24/outline instead of image

2023-02-09 07:51 UTC, nnanthicha requested changes

2023-02-09 07:51 UTC, nnanthicha commented on src/pages/user/booking/profile.tsx
> +            <path fillRule="evenodd" d="M11.03 3.97a.75.75 0 010 1.06l-6.22 6.22H21a.75.75 0 010 1.5H4.81l6.22 6.22a.75.75 0 11-1.06 1.06l-7.5-7.5a.75.75 0 010-1.06l7.5-7.5a.75.75 0 011.06 0z" clipRu
I mean you can import and use it like this `<ArrowLeftIcon  />` to make it short.

2023-02-10 13:16 UTC, closed without merging