feat: Add address auto complete
2110336-2565-2/sec2-group11-trainder-frontend pull request #21
Opened 2023-02-12 14:56 UTC by nopparuj917

- Add address auto complete
- Using the Google Maps Places API

2023-02-12 15:33 UTC, nopparuj917 commented
@nnanthicha Can you make the option as cute as Mean's girlfriend (Proud)

2023-02-13 03:49 UTC, noppakorn requested changes

2023-02-13 03:49 UTC, noppakorn commented on README.md
> +```
we only use yarn

2023-02-13 10:04 UTC, noppakorn requested changes

2023-02-13 10:04 UTC, noppakorn commented on src/pages/account/signup.tsx
> +  const renderForm = (i: number) => {
I'm not sure about this but is there any reason for putting this function inside of the Signup function. Can you explain a bit?

2023-02-13 10:04 UTC, noppakorn commented on src/components/places.tsx
> +  };
Should this be under useCallback?

2023-02-13 13:50 UTC, noppakorn approved these changes

2023-02-13 13:55 UTC, merged