Filter trainer UI
2110336-2565-2/sec2-group11-trainder-frontend pull request #23
Opened 2023-02-12 15:28 UTC by Ponrawoot

2023-02-12 16:20 UTC, noppakorn requested changes

2023-02-12 16:20 UTC, noppakorn commented on package.json
> +    "@mui/icons-material": "^5.11.0",
why?

2023-02-12 16:20 UTC, noppakorn commented on src/pages/user/booking/index.tsx
> +import Rating from "@mui/material/Rating";
why?

2023-02-12 16:20 UTC, noppakorn commented on src/pages/_app.tsx
> +    const publicPaths = ["/", "/account/signup","/user/booking"];
please do not forget about this

2023-02-13 09:30 UTC, nnanthicha requested changes
merge main into your branch and update code

2023-02-13 10:07 UTC, noppakorn requested changes
Same as nan, merge the main branch into your code.

2023-02-13 13:59 UTC, noppakorn approved these changes

2023-02-13 14:10 UTC, merged