Fix conflicts in review-ui branch
2110336-2565-2/sec2-group11-trainder-frontend pull request #68
Opened 2023-03-12 05:28 UTC by Ponrawoot

2023-03-12 05:35 UTC, noppakorn approved these changes
Looks good, wait for @nnanthicha review and merge

2023-03-12 05:57 UTC, nnanthicha requested changes

2023-03-12 05:57 UTC, nnanthicha commented on src/pages/user/review/[username].tsx
> +                              <EmptyStar />
the stars should be able to click to rate the trainer

2023-03-12 05:57 UTC, nnanthicha commented on src/pages/user/review/[username].tsx
> +        <svg
you should use `<StarIcon classname='.....' />` form heroicons instead of this long svg

2023-03-12 05:57 UTC, nnanthicha commented on src/pages/user/review/[username].tsx
> +        <img
I already remove this and use `<Image ....... />` from next/Image, please check main branch and fix this.

2023-03-12 05:57 UTC, nnanthicha commented on src/pages/user/review/[username].tsx
> +          <div className="mt-[20%]"></div>
I already fix the padding and position of main items in this page, you should look at main branch because this will overlap with navbar.

2023-03-12 05:57 UTC, nnanthicha commented on src/pages/user/review/[username].tsx
> +            <Image />
use next/Image as I mentioned above (just copy from main branch)

2023-03-12 06:09 UTC, nnanthicha commented
If you have time, you may change to use Dialog from headlessui (the modal behavioral is better this), but if you don't, it's ok.

2023-03-13 11:27 UTC, nnanthicha approved these changes

2023-03-13 11:29 UTC, merged