Chat
2110336-2565-2/sec2-group11-trainder-frontend pull request #79
Opened 2023-03-29 14:28 UTC by naphatbass

2023-03-29 15:52 UTC, noppakorn requested changes

2023-03-29 15:52 UTC, noppakorn commented on src/pages/user/chat.tsx
> +    <div
more margin and padding? I think each chat box is too close to each other.

2023-03-30 04:09 UTC, nnanthicha requested changes
Also fix margin or padding

2023-03-30 04:09 UTC, nnanthicha commented on src/pages/user/chat.tsx
> +      {showModal && (
I just create component template for modal, use that one instead.

2023-03-30 08:37 UTC, nnanthicha commented on src/pages/user/chat.tsx
> +  const [isClicked, setIsClicked] = useState(false);
click behavioral is not correct, it should be gray only one box at a time.

2023-03-31 02:02 UTC, noppakorn approved these changes
Wait for @nnanthicha review

2023-03-31 07:24 UTC, nnanthicha approved these changes

2023-03-31 07:25 UTC, merged