Filter trainer
2110336-2565-2/sec2-group11-trainder-frontend pull request #9
Opened 2023-02-08 06:26 UTC by Ponrawoot

2023-02-10 02:10 UTC, nnanthicha requested changes

2023-02-10 02:10 UTC, nnanthicha commented on src/pages/_app.tsx
> +    const publicPaths = ["/", "/account/signup", "/user/booking","/account/profile"];
Remove those paths from public paths

2023-02-10 02:10 UTC, nnanthicha commented on src/pages/user/booking/index.tsx
> +        </nav>
Import and use navbar from component instead

2023-02-11 08:13 UTC, noppakorn approved these changes

2023-02-11 08:20 UTC, nnanthicha approved these changes

2023-02-11 08:23 UTC, merged